name: Compile LaTeX Syllabus
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: nombre_de_tu_archivo.tex # El código que te pasé antes
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Plan_Clases_2026
          path: nombre_de_tu_archivo.pdf
