name: Compile LaTeX Syllabus
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # Aquí ponemos el nombre EXACTO de tu archivo .tex
          root_file: Plan_Clases_MeIAPC_2026.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Plan_Clases_2026
          # Aquí el nombre del PDF que se generará (mismo nombre que el .tex pero .pdf)
          path: Plan_Clases_MeIAPC_2026.pdf
